### ISSUE TITLE
Provide expanded additional attributes information for the Python MAAP config file

### ISSUE THREAD

**Issue by spa0002** [MAAP-Project/maap-py#8]
There are currently not enough indexed attributes listed in the MAAP config file. The following link contains a list of additional attributes to add, as well as the parameter names for the attributes [https://docs.google.com/document/d/1Il_1K23_UTWopMKANVQwr0mHQiiq4F8B9eU0oTZBh8g/edit](url).

**Comment by bsatoriu** [comment]
@spa0002 can you please provide the data type of each of these attributes? CMR requires this field. According to [this CMR doc](https://wiki.earthdata.nasa.gov/display/CMR/Additional+Attributes), the supported data types are: STRING, FLOAT, INT, BOOLEAN, DATE, TIME, DATETIME, DATE_STRING, TIME_STRING, DATETIME_STRING

Thanks!

**Comment by spa0002** [comment]
@bsatoriu I believe this document contains all of the attribute data types in the sections with detailed descriptions - https://docs.google.com/document/d/1aMHm6RZYUDdUrdVaugOMSDd64Iq6vaFfwv5dAAx49Lg/edit#heading=h.gjdgxs

**Comment by bsatoriu** [comment]
Thanks, @spa0002 . The attributes in maap-py are now up to date with your document: https://github.com/MAAP-Project/maap-py/blob/master/maap.cfg#L28

**Comment by spa0002** [comment]
Thanks @bsatoriu
